MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  WEIGHT: "/traffic-analysis/traffic/models/COCOPretrained/e2e_mask_rcnn_R_50_FPN_1x_no_head.pth"
  BACKBONE:
    CONV_BODY: "R-50-FPN"
    FREEZE_CONV_BODY_AT: -1
  RESNETS:
    BACKBONE_OUT_CHANNELS: 256
  RPN:
    USE_FPN: True
    ANCHOR_STRIDE: (4, 8, 16, 32, 64)
  ROI_HEADS:
    USE_FPN: True
    SCORE_THRESH: 0.15
    DETECTIONS_PER_IMG: 200
    NMS: 0.5
  ROI_BOX_HEAD:
    POOLER_RESOLUTION: 7
    POOLER_SCALES: (0.25, 0.125, 0.0625, 0.03125)
    POOLER_SAMPLING_RATIO: 2
    FEATURE_EXTRACTOR: "FPN2MLPFeatureExtractor"
    PREDICTOR: "FPNPredictor"
    NUM_CLASSES: 7
  MASK_ON: False
DATASETS:
  TRAIN: ("traffic_train", )
  TEST: ("traffic_eval", )
DATALOADER:
  SIZE_DIVISIBILITY: 32
  NUM_WORKERS: 4
SOLVER:
  BASE_LR: 0.001
  WEIGHT_DECAY: 0.0001
  STEPS: (20000, 27000)
  MAX_ITER: 30000
  IMS_PER_BATCH: 4
  CHECKPOINT_PERIOD: 1000

  WARMUP_FACTOR: 25.0
  WARMUP_ITERS: 1000
  WARMUP_LAYERS: ("rpn.head.cls_logits.weight", "rpn.head.cls_logits.bias",
    "rpn.head.bbox_pred.weight", "rpn.head.bbox_pred.bias",
    "roi_heads.box.predictor.cls_score.weight", "roi_heads.box.predictor.cls_score.bias",
    "roi_heads.box.predictor.bbox_pred.weight", "roi_heads.box.predictor.bbox_pred.bias",
    "roi_heads.mask.predictor.conv5_mask.weight", "roi_heads.mask.predictor.conv5_mask.bias",
    "roi_heads.mask.predictor.mask_fcn_logits.weight", "roi_heads.mask.predictor.mask_fcn_logits.bias")
TEST:
  IMS_PER_BATCH: 3
INPUT:
  MIN_SIZE_TRAIN: (512, )
  MAX_SIZE_TRAIN: 1280
  MIN_SIZE_TEST: 512
  MAX_SIZE_TEST: 1280
PATHS_CATALOG: "/traffic-analysis/traffic/paths_catalog.py"
